apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: a-counter
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sika-training-examples/2023-10-23-counter-eon-helm.git
    targetRevision: HEAD
    path: .
    helm:
      releaseName: counter
      values: |
        host: a-counter.eon.sikademo.com
        replicas: 4
